{application,zigbee_provider,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{zigbee_provider_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[zigbee_provider,zigbee_provider_app,
                        zigbee_provider_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
